version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: movie-rating-backend-dev
    ports:
      - "3000:3000"
    environment:
      NEO4J_URI: bolt://host.docker.internal:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test1234
    extra_hosts:
      - "host.docker.internal:host-gateway"