version: "3.8"

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5
    container_name: movie-rating-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/test1234
    volumes:
      - neo4j_data:/data

  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: movie-rating-backend
    ports:
      - "3000:3000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test1234
    depends_on:
      - neo4j

volumes:
  neo4j_data:

